# Generated by Django 5.2.5 on 2025-09-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
